# Generated by Django 6.0.4 on 2026-04-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_auto_20260413_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="tasks.taskstatus",
            ),
        ),
    ]
