# Generated by Django 6.0.4 on 2026-04-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_auto_20260413_1636"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
    ]
