# Generated by Django 6.0.4 on 2026-04-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_remove_task_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="status_fk",
            new_name="status",
        ),
    ]
