# Generated by Django 6.0.4 on 2026-04-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_rename_status_fk_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
